### PR TITLE
I have no clue what I’m doing.

### PR DESCRIPTION
**Pull request by NekWasTaken**
You see, I’m mega retarted to the max and Python bad.

### CODE REVIEW

**Comment by Nirlep5252** [comment]
why

**Comment by Nirlep5252** [comment]
just why

**Comment by NekWasTaken** [comment]
T e x t. F o r m a t i n g

**Comment by NekWasTaken** [comment]
As you can see, I have no idea what I’m doing.

**Comment by Nirlep5252** [comment]
u know what i'll merge it just cuz why not

**Comment by NekWasTaken** [comment]
Oh so I didn’t break it?

**Comment by Nirlep5252** [comment]
greetings thing broke but thats not the code idk what but yeah

**Pull request merged**
