### PR TITLE
Automod commands rewrite using group commands

### PR DESCRIPTION
**Pull request by MrPotato374**
heh

### CODE REVIEW

**Comment by Nirlep5252** [comment]
👀

**Comment by Nirlep5252** [comment]
this gonna be the most epik pr 👀

**Review by Nirlep5252 — APPROVED** [review]

**Comment by brixk** [comment]
prank!!!!

**Comment by Nirlep5252** [comment]
:scared:

**Comment by MrPotato374** [comment]
AJAJAJA

**Comment by MrPotato374** [comment]
WOKWOKWOWKASD

**Comment by Nirlep5252** [comment]
:drunktato:

**Comment by Nirlep5252** [comment]
.

**Comment by Nirlep5252** [comment]
TODO: rewrite actual backside automod module handlers, and switch it to some other cog like `mod/config`
Also thanks a lot @MrPotato374 ❤️

**Comment by Nirlep5252** [comment]
^ todo for me dw about it lmao
keeping it so i dont forget

**Comment by MrPotato374** [comment]
nirlep best coder!

**Comment by MrPotato374** [comment]
:orz: masterlep!

**Comment by Nirlep5252** [comment]
Merging, thanks a lot @MrPotato374 <3

**Pull request merged**
