### PR TITLE
Fixed your shitty eval

### PR DESCRIPTION
**Pull request by Motzumoto**
convert it to fix your weird ass "client" shit, like who uses client

### CODE REVIEW

**Comment by Motzumoto** [comment]
Suggestion, use your own custom permissions system so you can use your commands even if you dont have the permissions. What i do is i put people i trust in my config, they have god powers now. You should do the same

**Review by ZeroTwoDev — COMMENTED** [review]
lol no u

**Comment by Motzumoto** [comment]
> lol no u

ugly

**Comment by Nirlep5252** [comment]
e

**Pull request merged**
