### PR TITLE
fix reaction roles (hope i didnt make any mistake)

### PR DESCRIPTION
**Pull request by MrPotato374**
pls work now

### CODE REVIEW

**Comment by MrPotato374** [comment]
image
this was the bug if you dont know (people were confused in Discord)

**Comment by MrPotato374** [comment]
it shows this first:
image
and in like 1 second the description changed to this 
image
**BIG BUGG**

**Comment by MrPotato374** [comment]
this isnt the best way to do it nirlep has some others ways idk about that but this thing will work for now change the code if u need to nirlep to the BEST MASTER CODE POG AMAZING WONDERFUL :)) good luck for ur exams that is coming btw

**Comment by Nirlep5252** [comment]
thanks a lot! sorry for late response

**Pull request merged**
