### PR TITLE
A Trash Giveaway System

### PR DESCRIPTION
**Pull request by KiritoGuy**
Screenshot_2021_1110_135859
Trash Giveaway System that you will never like to use

### CODE REVIEW

**Comment by Nirlep5252** [comment]
veri cool thankx
i'll review it in a few days 👌

**Comment by KiritoGuy** [comment]
ok :)

**Comment by JohnnyJTH** [comment]
Using sleep....

**Comment by Nirlep5252** [comment]
This giveaway system won't be that great as it stops all giveaways after it restarts
+ I want it to be integrated with the leveling system where you can set level requirements or message requirements

Sorry but I can't merge this for now

**Pull request closed without merging**
