### PR TITLE
Snake cmd

### PR DESCRIPTION
**Pull request by KiritoGuy**
Snake Command but it has some rate limited errors. Plz fix that ratelimited thing if you can 😭

### CODE REVIEW

**Comment by MrPotato374** [comment]
this code looks familiar 🤔

**Comment by MrPotato374** [comment]
is this from [here](https://github.com/skylarr1227/sky-cogs/blob/master/snake/snake.py)-

**Comment by Nirlep5252** [comment]
Please don't PR stolen code

**Comment by KiritoGuy** [comment]
ok. I thought that might help epikbot. I won't pr again. Sorry!

**Pull request closed without merging**
